### ISSUE TITLE
SSH connection can not be extabished with JSch after I reboot the target server and pop exception "Algorithm negotiation fail "

### ISSUE THREAD

**Issue by mysjz-qingquanshishangliu** [mwiede/jsch#111]
**Environment:**
JSch: 0.1.60
OpenSSH: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
java : 1.8

**Issue,**
I use the JSch to extablish the ssh connection to server A, it ran successfully. Until reboot the server A, the connection nerver can be estabished and pop the exception "Algorithm negotiation fail". At the same time, there are server B and C, it run successfully. it is confusing for me. The code is same, why the result is different.
Anyone has any advice, how can I resolve the issue. I guess it is an issue about server A configuration, or someone change the server configuration and reboot the server, but not sure what cause it.

**code,**
 `public void keyLogin(String user, String host, int port, String keyPath, Map<String, Integer> ptySizeMap)
			throws JSchException, IOException {
		JSch jsch = new JSch();
		jsch.addIdentity(keyPath);

		session = jsch.getSession(user, host, port);
		this.connect(ptySizeMap);
	}

	private void connect(Map<String, Integer> ptySizeMap) throws JSchException, IOException {
		try {
			session.setConfig("StrictHostKeyChecking", "no");
			session.connect(30000); // making a connection with timeout. 30s
			channel = (ChannelShell) session.openChannel("shell");
			inputStream = channel.getInputStream();
			outputStream = channel.getOutputStream();
			Integer col = ptySizeMap.get("col") == null ? 80 : ptySizeMap.get("col");
			Integer row = ptySizeMap.get("row") == null ? 24 : ptySizeMap.get("row");
			Integer wp = ptySizeMap.get("wp") == null ? 640 : ptySizeMap.get("wp");
			Integer hp = ptySizeMap.get("hp") == null ? 480 : ptySizeMap.get("hp");
			channel.setPtyType("xterm");
			channel.setPtySize(col, row, wp, hp);
			channel.connect(30000); // making a connection with timeout. 30s			
		} catch (JSchException e) {
			//String。contains()可能存在JDK版本沖突
			if(null != e.getMessage() && e.getMessage().indexOf("channel is not opened") != -1){
				throw new JSchException("SSH connection timeout");
			}
			throw e;
		}
	}`

**log,**
```
2022-01-20 21:46:08 [ERROR]-[com.dawning.gridview.app.webshell.application.clustertool.eshell.ShellPlatform.classifyProcessException(ShellPlatform.java:221)] com.jcraft.jsch.JSchException: Algorithm negotiation fail 
java.lang.Throwable: com.jcraft.jsch.JSchException: Algorithm negotiation fail
        at com.jcraft.jsch.Session.receive_kexinit(Session.java:593)
        at com.jcraft.jsch.Session.connect(Session.java:323)
```

**Comment by norrisjeremy** [comment]
1. Can you use the CLI command `ssh -vvv w.x.y.z` where `w.x.y.z` is the server A IP address or hostname and capture it’s output? This will let us see what crypto algorithms the server is advertising, which likely aren’t compatible with the algorithms supported by the default JSch configuration.
2. 0.1.60 is an older release: have you tried using a newer release?

**Comment by mysjz-qingquanshishangliu** [comment]
I have pasted the ssh -vvv *.*.*.* info like below. have not tried the latest jSch version, Is there any way to fix this issue via server configuration?
```
[root@admin1 ~]# ssh -vvv admin1
OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /root/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug2: resolving "admin1" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to admin1 [10.10.10.57] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: identity file /root/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: match: OpenSSH_7.4 pat OpenSSH* compat 0x04000000
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to admin1:22 as 'root'
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file /root/.ssh/known_hosts:7
debug3: load_hostkeys: loaded 1 keys from admin1
debug3: order_hostkeyalgs: prefer hostkeyalgs: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
debug2: host key algorithms: ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,blowfish-cbc,cast128-cbc,3des-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-ed25519 SHA256:JXwERPXNX46Dc+8PZtKNLLK+7/zS53x6FQY8ddzBt/E
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file /root/.ssh/known_hosts:7
debug3: load_hostkeys: loaded 1 keys from admin1
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ED25519 in file /root/.ssh/known_hosts:3
debug3: load_hostkeys: loaded 1 keys from 10.10.10.57
debug1: Host 'admin1' is known and matches the ED25519 host key.
debug1: Found key in /root/.ssh/known_hosts:7
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 134217728 blocks
debug2: key: /root/.ssh/id_rsa (0x55fb2bb096b0)
debug2: key: /root/.ssh/id_dsa ((nil))
debug2: key: /root/.ssh/id_ecdsa ((nil))
debug2: key: /root/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,gssapi-keyex,gssapi-with-mic,password
debug3: start over, passed a different list publickey,gssapi-keyex,gssapi-with-mic,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup gssapi-keyex
debug3: remaining preferred: gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-keyex
debug1: Next authentication method: gssapi-keyex
debug1: No valid Key exchange context
debug2: we did not send a packet, disable method
debug3: authmethod_lookup gssapi-with-mic
debug3: remaining preferred: publickey,keyboard-interactive,password
debug3: authmethod_is_enabled gssapi-with-mic
debug1: Next authentication method: gssapi-with-mic
debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KEYRING:persistent:0)

debug1: Unspecified GSS failure.  Minor code may provide more information
No Kerberos credentials available (default cache: KEYRING:persistent:0)

debug2: we did not send a packet, disable method
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /root/.ssh/id_rsa
debug3: send_pubkey_test
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: pkalg rsa-sha2-512 blen 279
debug2: input_userauth_pk_ok: fp SHA256:SHUCw5Aqhy3vcBtqz0oUseXOKw3zctLRVORJIFSb4yo
debug3: sign_and_send_pubkey: RSA SHA256:SHUCw5Aqhy3vcBtqz0oUseXOKw3zctLRVORJIFSb4yo
debug3: send packet: type 50
debug3: receive packet: type 52
debug1: Authentication succeeded (publickey).
Authenticated to admin1 ([10.10.10.57]:22).
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: network
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: receive packet: type 91
debug2: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: ssh_packet_set_tos: set IP_TOS 0x10
debug2: client_session2_setup: id 0
debug2: channel 0: request pty-req confirm 1
debug3: send packet: type 98
debug1: Sending environment.
debug3: Ignored env MKLROOT
debug3: Ignored env MANPATH
debug3: Ignored env XDG_SESSION_ID
debug3: Ignored env HOSTNAME
debug3: Ignored env INTEL_LICENSE_FILE
debug3: Ignored env SLURM_PMIX_DIRECT_CONN_UCX
debug3: Ignored env TERM
debug3: Ignored env SHELL
debug3: Ignored env HISTSIZE
debug3: Ignored env SSH_CLIENT
debug3: Ignored env PERL5LIB
debug3: Ignored env LIBRARY_PATH
debug3: Ignored env FPATH
debug3: Ignored env QTDIR
debug3: Ignored env QTINC
debug3: Ignored env PERL_MB_OPT
debug3: Ignored env SSH_TTY
debug3: Ignored env CLUSCONF_HOME
debug3: Ignored env QT_GRAPHICSSYSTEM_CHECKED
debug3: Ignored env USER
debug3: Ignored env LD_LIBRARY_PATH
debug3: Ignored env LS_COLORS
debug3: Ignored env CPATH
debug3: Ignored env NLSPATH
debug3: Ignored env NFSCONF
debug3: Ignored env MAIL
debug3: Ignored env PATH
debug3: Ignored env BATCH_EXECUTION_STATUS
debug3: Ignored env C_INCLUDE_PATH
debug3: Ignored env TBBROOT
debug3: Ignored env PWD
debug3: Ignored env IPMICONF
debug1: Sending env LANG = en_US.UTF-8
debug2: channel 0: request env confirm 0
debug3: send packet: type 98
debug3: Ignored env MODULEPATH
debug3: Ignored env SLURM_PMIX_TIMEOUT
debug3: Ignored env LOADEDMODULES
debug3: Ignored env KDEDIRS
debug3: Ignored env AUTOCLUSCONF
debug3: Ignored env GRIDVIEW_HOME
debug3: Ignored env PERLLIB
debug3: Ignored env SLURM_HOME
debug3: Ignored env SSH_ASKPASS
debug3: Ignored env HISTCONTROL
debug3: Ignored env SHLVL
debug3: Ignored env HOME
debug3: Ignored env SLURM_PMIX_DIRECT_CONN
debug3: Ignored env PERL_LOCAL_LIB_ROOT
debug3: Ignored env LOGNAME
debug3: Ignored env QTLIB
debug3: Ignored env CVS_RSH
debug3: Ignored env STARTWAITTIME
debug3: Ignored env XDG_DATA_DIRS
debug3: Ignored env SSH_CONNECTION
debug3: Ignored env MODULESHOME
debug3: Ignored env LESSOPEN
debug3: Ignored env PMIX_HOME
debug3: Ignored env MUNGE_HOME
debug3: Ignored env XDG_RUNTIME_DIR
debug3: Ignored env QT_PLUGIN_PATH
debug3: Ignored env INCLUDE
debug3: Ignored env PERL_MM_OPT
debug3: Ignored env SLURM_PMIX_DIRECT_CONN_EARLY
debug3: Ignored env BASH_FUNC_module()
debug3: Ignored env _
debug2: channel 0: request shell confirm 1
debug3: send packet: type 98
debug2: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: PTY allocation request accepted on channel 0
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: shell request accepted on channel 0

```

**Comment by norrisjeremy** [comment]
Your server is configured to only use `ssh-ed25519` type host keys:
```
debug2: peer server KEXINIT proposal
...
debug2: host key algorithms: ssh-ed25519
```

You will need to do one of the following:
1. Reconfigure your server to allow more than just `ssh-ed25519` type host keys.
2. Upgrade from Java 8 to Java 15 or newer and use the latest JSch releease.
3. Use the latest JSch release & add [Bouncy Castle](https://www.bouncycastle.org/java.html) (bcprov-jdk15on) to your application's classpath (this would let you stay with Java 8).

**Comment by mysjz-qingquanshishangliu** [comment]
Thanks for your great response, for the first suggestion: How I can reconfigure the server ?

**Comment by norrisjeremy** [comment]
> Thanks for your great response, for the first suggestion: How I can reconfigure the server ?

This isn't really a forum for server administration advice. I'd suggest speaking with your server's administrators or using a general support forum like [Server Fault](https://serverfault.com/).
