### ISSUE TITLE
SSH_MSG_DISCONNECT: 2 The connection is closed by SSH server

### ISSUE THREAD

**Issue by zhanglinqiang** [mwiede/jsch#112]
Hello, I have a Huawei switch() device connection failure again. Using ssh command from server connected well. Can anyone help me take a look？

Jsch version:
```
<dependency>
            <groupId>com.github.mwiede</groupId>
            <artifactId>jsch</artifactId>
            <version>0.1.72</version>
        </dependency>
```
Java version:
```
root@19ea16cb5e0f:/# java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

StackTrace:
```
23:54:21,016 [pool-6-thread-5] ERROR com.topsec.tap.collector.agent.pg.av - SSH_MSG_DISCONNECT: 2 The connection is closed by SSH server
  
com.jcraft.jsch.JSchException: SSH_MSG_DISCONNECT: 2 The connection is closed by SSH server
  
	at com.jcraft.jsch.Session.read(Session.java:1260)
	at com.jcraft.jsch.UserAuthKeyboardInteractive.start(UserAuthKeyboardInteractive.java:78)
	at com.jcraft.jsch.Session.connect(Session.java:475)
	at com.topsec.tap.collector.agent.pg.av.g(JschConnection.java:233)
	at com.topsec.tap.collector.agent.pg.av.open(JschConnection.java:140)
	at com.topsec.tap.collector.agent.pg.ao.a(Connection.java:68)
	at com.topsec.tap.collector.agent.pg.ao.b(Connection.java:64)
	at com.topsec.tap.collector.agent.pg.bZ.call(TimeoutExecution.java:61)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

ssh info via 'ssh -vvv':
```
[root@localhost /]# ssh -vvv 192.168.2.2
OpenSSH_8.0p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug2: resolving "192.168.2.2" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to 192.168.2.2 [192.168.2.2] port 22.
debug1: Connection established.
debug1: permanently_set_uid: 0/0
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /root/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version -
debug1: no match: -
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to 192.168.2.2:22 as 'root'
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 192.168.2.2
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c
debug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1
debug2: host key algorithms: ecdsa-sha2-nistp521,ssh-dss,ssh-rsa
debug2: ciphers ctos: aes256-ctr,aes128-ctr
debug2: ciphers stoc: aes256-ctr,aes128-ctr
debug2: MACs ctos: hmac-sha2-256
debug2: MACs stoc: hmac-sha2-256
debug2: compression ctos: none,zlib
debug2: compression stoc: none,zlib
debug2: languages ctos:
debug2: languages stoc:
debug2: first_kex_follows 0
debug2: reserved 0
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: ecdsa-sha2-nistp521
debug1: kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: diffie-hellman-group-exchange-sha256 need=32 dh_need=32
debug1: kex: diffie-hellman-group-exchange-sha256 need=32 dh_need=32
debug3: send packet: type 34
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST(1024<8192<8192) sent
debug3: receive packet: type 31
debug1: got SSH2_MSG_KEX_DH_GEX_GROUP
debug2: bits set: 2048/4096
debug3: send packet: type 32
debug1: SSH2_MSG_KEX_DH_GEX_INIT sent
debug3: receive packet: type 33
debug1: got SSH2_MSG_KEX_DH_GEX_REPLY
debug1: Server host key: ecdsa-sha2-nistp521 SHA256:B0tVLMZaHGZa2rFQwzFnT81wBczO3rxxh8yhR+g6ybY
debug3: hostkeys_foreach: reading file "/root/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /root/.ssh/known_hosts:1
debug3: load_hostkeys: loaded 1 keys from 192.168.2.2
debug1: Host '192.168.2.2' is known and matches the ECDSA host key.
debug1: Found key in /root/.ssh/known_hosts:1
debug2: bits set: 2090/4096
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey after 4294967296 blocks
debug2: key: /root/.ssh/id_rsa ((nil))
debug2: key: /root/.ssh/id_dsa ((nil))
debug2: key: /root/.ssh/id_ecdsa ((nil))
debug2: key: /root/.ssh/id_ed25519 ((nil))
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,keyboard-interactive,password
debug3: start over, passed a different list publickey,keyboard-interactive,password
debug3: preferred gssapi-keyex,gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /root/.ssh/id_rsa
debug3: no such identity: /root/.ssh/id_rsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_dsa
debug3: no such identity: /root/.ssh/id_dsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ecdsa
debug3: no such identity: /root/.ssh/id_ecdsa: No such file or directory
debug1: Trying private key: /root/.ssh/id_ed25519
debug3: no such identity: /root/.ssh/id_ed25519: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup keyboard-interactive
debug3: remaining preferred: password
debug3: authmethod_is_enabled keyboard-interactive
debug1: Next authentication method: keyboard-interactive
debug2: userauth_kbdint
debug3: send packet: type 50
debug2: we sent a keyboard-interactive packet, wait for reply
debug3: receive packet: type 60
debug2: input_userauth_info_req
User Authentication
debug2: input_userauth_info_req: num_prompts 1
Password:

```

Jsch config:
```
static {

        appendJschConfig("kex", "diffie-hellman-group1-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1");

        appendJschConfig("server_host_key", "ssh-dss");

        appendJschConfig("cipher.s2c", "aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc");
        appendJschConfig("cipher.c2s", "aes128-cbc,3des-cbc,aes192-cbc,aes256-cbc");
        appendJschConfig("mac.s2c", "hmac-sha1-96,hmac-md5,hmac-md5-96");
        appendJschConfig("mac.c2s", "hmac-sha1-96,hmac-md5,hmac-md5-96");

        JSch.setConfig("StrictHostKeyChecking", "no");
        JSch.setConfig("PreferredAuthentications", "password,keyboard-interactive");
        //Solaris
        JSch.setConfig("dhgex_preferred", "1024");
        JSch.setConfig("dhgex_min", "1024");
    }

    private static void appendJschConfig(String key, String value) {
        String oldConfig = JSch.getConfig(key);
        String collect = Stream.concat(Arrays.stream(oldConfig.split(",")), Arrays.stream(value.split(",")))
                .distinct()
                .collect(Collectors.joining(","));
        JSch.setConfig(key, collect);
    }
```

**Comment by norrisjeremy** [comment]
Does it work if you change to this?
```
JSch.setConfig("PreferredAuthentications", "keyboard-interactive,password");
```

**Comment by zhanglinqiang** [comment]
I referred to the advice on this link ‘https://support.huawei.com/enterprise/en/knowledge/EKB1002019528’
After executing these two commands
···
ssh server compatible-ssh1x enable
RSA local-key-pair create
···
It works, But this reduces the security of the device. I don't know if this is a problem for jsch.

**Comment by zhanglinqiang** [comment]
> Does it work if you change to this?
> 
> ```
> JSch.setConfig("PreferredAuthentications", "keyboard-interactive,password");
> ```

I remembered, when I use the ssh command to connect to this switch on the Linux system, the password prompt appears very slowly, about 10s or more, but the timeout of Jsch I set is 2 minutes.
```
 session = jSch.getSession(this.userName, this.hostIp, this.port);
            session.setPassword(this.userPwd);

            session.connect(120000);
            isLogin = session.isConnected();
            if (!isLogin) {
                log.error("Login Failed userName or password error!" + this.hostIp);
                throw new ConnectException("Login Failed");
            }
```
Your suggestion about modifying "PreferredAuthentications" I need to try it later, thanks a lot for the reply

**Comment by zhanglinqiang** [comment]
> I referred to the advice on this link ‘[https://support.huawei.com/enterprise/en/knowledge/EKB1002019528’](https://support.huawei.com/enterprise/en/knowledge/EKB1002019528%E2%80%99) After executing these two commands ··· ssh server compatible-ssh1x enable RSA local-key-pair create ··· It works, But this reduces the security of the device. I don't know if this is a problem for jsch.

Hi! I found that the connected has nothing to do with this configuration, because after I disable ssh1 compatibility, the program can still connect successfully when PreferredAuthentications set to "password,keyboard-interactive".

The reason I config "PreferredAuthentications" separately is because the default value will cause most legacy devices (only support password) to fail the connection. 

I think you're correct in locating the problem, when the negotiation with the target device is delayed for some reason, it might cause the problem.

Does this mechanism need to be optimized? Or provide a parameter to adjust the timeout?

**Comment by norrisjeremy** [comment]
I am a bit confused: you initially reported that it didn't work with PreferredAuthentications set to "password,keyboard-interactive", but now you are stating it is working?
Or did you mean it still doesn't work with "password,keyboard-interactive", but it does work with "keyboard-interactive,password"?

**Comment by zhanglinqiang** [comment]
> I am a bit confused: you initially reported that it didn't work with PreferredAuthentications set to "password,keyboard-interactive", but now you are stating it is working? Or did you mean it still doesn't work with "password,keyboard-interactive", but it does work with "keyboard-interactive,password"?

I am also confused about this situation. Now that PreferredAuthentications is set to "password,keyboard-interactive", the connection can be successfully connected. This may be an occasional problem. As I mentioned, the default settings may cause some devices(only provide password) to fail to connect, which I'm guessing could be the same problem. I don't know much about the connection establishment process of jsch, so I just wonder if the connection process can handle this kind of problem by adjusting the logic without adjusting the value of PreferredAuthentications. In my program, PreferredAuthentications is set globally, if only By modifying the value of PreferredAuthentications I may need to set it individually for each session.

Since this problem no longer exists，I will close this issue. Thanks a lot for your reply.

**Comment by norrisjeremy** [comment]
The way the SSH protocol works, there isn't a way for the server to advertise to the client what authentication methods it supports. So the client has to iterate through each of the PreferredAuthentications, trying each one to see if it works with the server. Each of which are attempted by the client and do not work, are considered a failed authentication attempt by the server. Servers also typically have a limit on the number of failed auth attempts a client can attempt before it will close the connection (for OpenSSH based servers this is the MaxAuthTries).

I believe this may be what you were seeing: the device you were attempting to connect to was closing the connection while JSch was performing its authentication probe attempts to find an authentication method that worked. This is why I initially suggested changing the order to "keyboard-interactive,password" to see if it fixed the problem.

**Comment by zhanglinqiang** [comment]
OK, I see, thanks for the detailed explanation.

**Comment by a1078619054** [comment]
相信你可能已经解决了，我说一下我的看法，这种问题建议使用wireshark抓包看看，你这种情况可能是ssh协议协商没有成功，可能性很多，比如加密算法等；我刚遇到这个问题，我不懂编程，但从抓包看 ssh.dh_gex.max 2048是这个；而华为最新配置一般配置为ssh server dh-exchange min-len 3072,导致协商不成功
