### ISSUE TITLE
intermittent "JSchException: connection is closed by foreign host"

### ISSUE THREAD

**Issue by avnerw74** [mwiede/jsch#123]
Hi,

We are facing an issue while using v0.1.55 when having multiple (few dozens of) concurrent connections to sshd server on Linux.
While most of the connections succeed, few of them failed with "JSchException: connection is closed by foreign host".

com.jcraft.jsch.JSchException: connection is closed by foreign host
	at com.jcraft.jsch.Session.connect(Session.java:285) ~[classes!/:?]
	at com.jcraft.jsch.Session.connect(Session.java:195) ~[classes!/:?]
	...
	
We noticed that in these cases, the client doesn't receive the SSH version and instead receives a "-1 byte" and therefore throws the exception.

So in more than 95% of the time, JSCH receives "SSH-2.0-OpenSSH_7.4" -> OK
But some of the time it receives byte -1 (empty response) -> NOT OK

I assume this is not JSCH fault, but wanted to check whether you encountered such an issue before, and to know:
1. Is there a limit to the number of concurrent JSCH objects we can create in a single process?
2. Do you have any idea what could cause the issue? We haven't seen anything special in the sshd log file.

Best Regards,
Avner

**Comment by avnerw74** [comment]
Hi @norrisjeremy ,

Thanks for the reply.
Yes, I noticed it is 10/30/100 and modified it to 1024. 
So far I haven't seen the issue with 1024.
I changed back to 10 and encountered it, so it might be the issue. I will continue testing and update.

BTW, do you know if I should also increase the MaxSessions? (as this is affecting the concurrent sessions, no?)
It doesn't appear in the sshd_config and I read it is set to 10 by default.

Best Regards,
Avner

**Comment by avnerw74** [comment]
Hi @norrisjeremy 

Thanks for the explanation.
Seems like it was the MaxStartups, I'll close the issue (and reopen only if the issue recreates)

Many Thanks,
Avner
