### ISSUE TITLE
Session failing to connect when providing user and password

### ISSUE THREAD

**Issue by gianielsevier** [mwiede/jsch#184]
I've moved from the original version of JSch-0.1.55 and solved the issue related to using modern ssh keys like OPEN SSL. However, when I try to open a connection using user/password instead of user/private-key I'm getting the following error:

```java
Caused by: com.jcraft.jsch.JSchException: Algorithm negotiation fail
	at com.jcraft.jsch.Session.receive_kexinit(Session.java:604)
	at com.jcraft.jsch.Session.connect(Session.java:334)
	at com.jcraft.jsch.Session.connect(Session.java:194)
	at org.springframework.integration.sftp.session.SftpSession.connect(SftpSession.java:294)
```

I'm using spring integration with jsch 0.2.2. 
This is the code snippet I'm using:
```java
SftpSession getSession() {

        var sftpSessionFactory = new DefaultSftpSessionFactory();
        sftpSessionFactory.setHost("HOST");
        sftpSessionFactory.setAllowUnknownKeys(true);
        sftpSessionFactory.setUser("USER");
        sftpSessionFactory.setPassword("PASS");
        
        return sftpSessionFactory.getSession();
    }
```
Is anyone having the same issue?

**Comment by norrisjeremy** [comment]
Hi @gianielsevier,

It is likely that the SSH server you are connecting to doesn't support the default set of crypto algorithms that JSch is configured to use.

Can you do one of the following to help troubleshoot to help see what crypto algorithms your server is advertising?
1. Run the CLI command `ssh -vvv w.x.y.z` where `w.x.y.z` is the SSH server IP address or hostname and capture it’s output? 
2. Enable JSch logging by adding `JSch.setLogger(...)` to your application somewhere before creating the SSH session and then capture it's output? There are a few built-in logger implementations that you can use, depending upon the type of logging framework you are using, such as `new JulLogger()`, `new Log4j2Logger()`, `new Slf4jLogger()` or `new JplLogger()`. You will also want to make sure verbose logging is enabled in your logging framework of choice for `com.jcraft.jsch.JSch`.

Thanks,
Jeremy

**Comment by gianielsevier** [comment]
Hi Jeremy,

Many thanks for you quick reply:

This is the output from the command you've suggested:
```shell
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data FILE
debug1: FILE line 84: Applying options for *
debug1: Reading configuration data FILE
debug1: FILE line 47: Applying options for *
debug1: Connecting to HOST port 22.
debug1: Connection established.
debug1: identity file FILE type 0
debug1: identity file FILE type -1
debug1: identity file FILE type -1
debug1: identity file FILEtype -1
debug1: identity file FILE type -1
debug1: identity file FILE type -1
debug1: identity file FILE type -1
debug1: identity file FILEtype -1
debug1: identity file FILE type -1
debug1: identity file FILE type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version FTP Server ready.
debug1: no match: FTP Server ready.
debug3: fd 5 is O_NONBLOCK
debug1: Authenticating to HOST:22 as 'USER'
debug3: hostkeys_foreach: reading file "FILE"
debug3: record_hostkey: found key type RSA in file FILE
debug3: load_hostkeys: loaded 1 keys from HOST
debug3: order_hostkeyalgs: prefer hostkeyalgs: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,ext-info-c
debug2: host key algorithms: rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa1024-sha1
debug2: host key algorithms: ssh-rsa,ssh-dss
debug2: ciphers ctos: aes128-ctr,aes192-ctr,aes256-ctr
debug2: ciphers stoc: aes128-ctr,aes192-ctr,aes256-ctr
debug2: MACs ctos: hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512
debug2: MACs stoc: hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512
debug2: compression ctos: zlib@openssh.com,zlib,none
debug2: compression stoc: zlib@openssh.com,zlib,none
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug1: kex: algorithm: ecdh-sha2-nistp256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: server->client cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug1: kex: client->server cipher: aes128-ctr MAC: umac-64@openssh.com compression: none
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: Server host key: ssh-rsa SHA256:NOPE
debug3: hostkeys_foreach: reading file "FILE"
debug3: record_hostkey: found key type RSA in file FILE
debug3: load_hostkeys: loaded 1 keys from HOST
debug3: hostkeys_foreach: reading file "FILE"
debug3: record_hostkey: found key type RSA in file FILE
debug3: load_hostkeys: loaded 1 keys from 130.14.29.14
debug1: Host 'HOST' is known and matches the RSA host key.
debug1: Found key in KEY:65
debug3: send packet: type 21
debug2: set_newkeys: mode 1
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: KEY RSA SHA256:NOPE
debug1: Will attempt key: KEY
debug1: Will attempt key: KEY
debug1: Will attempt key: KEY
debug1: Will attempt key: KEY
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 53
debug3: input_userauth_banner

BANNER
debug3: receive packet: type 51
debug1: Authentications that can continue: password
debug3: start over, passed a different list password
debug3: preferred publickey,keyboard-interactive,password
debug3: authmethod_lookup password
debug3: remaining preferred: ,keyboard-interactive,password
debug3: authmethod_is_enabled password

```

This is the log using the lib:
```shell
14:51:40.519 [main] INFO com.jcraft.jsch - Connecting to HOST
14:51:40.849 [main] INFO com.jcraft.jsch - Connection established
14:51:40.997 [main] INFO com.jcraft.jsch - Remote version string: SSH-2.0-FTP Server ready.
14:51:40.998 [main] INFO com.jcraft.jsch - Local version string: SSH-2.0-JSCH_0.2.2
14:51:40.998 [main] INFO com.jcraft.jsch - CheckCiphers: chacha20-poly1305@openssh.com
14:51:40.998 [main] INFO com.jcraft.jsch - CheckKexes: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
14:51:41.068 [main] INFO com.jcraft.jsch - CheckSignatures: ssh-ed25519,ssh-ed448
14:51:41.216 [main] DEBUG com.jcraft.jsch - server_host_key proposal before known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
14:51:41.220 [main] DEBUG com.jcraft.jsch - server_host_key proposal after known_host reordering is: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
14:51:41.220 [main] INFO com.jcraft.jsch - SSH_MSG_KEXINIT sent
14:51:41.220 [main] INFO com.jcraft.jsch - SSH_MSG_KEXINIT received
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group14-sha256,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,rsa1024-sha1
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: ssh-rsa,ssh-dss
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: aes128-ctr,aes192-ctr,aes256-ctr
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: aes128-ctr,aes192-ctr,aes256-ctr
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: hmac-sha1,umac-64@openssh.com,hmac-sha2-256,hmac-sha2-512
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: zlib@openssh.com,zlib,none
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: zlib@openssh.com,zlib,none
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: 
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: 
14:51:41.220 [main] INFO com.jcraft.jsch - kex: client: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: none
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: none
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: 
14:51:41.221 [main] INFO com.jcraft.jsch - kex: client: 
14:51:41.221 [main] INFO com.jcraft.jsch - Disconnecting from HOST port 22
```

Kind regards,
Giani Segatto

**Comment by norrisjeremy** [comment]
Hi @gianielsevier,

So it looks like your server only supports RSA/SHA1 type hostkeys, which are disabled now by default with JSch:
```
14:51:41.220 [main] INFO com.jcraft.jsch - kex: server: ssh-rsa,ssh-dss
```

You will need to explicitly enable the `ssh-rsa` (RSA/SHA1) hostkey algorithm with JSch to support this server.
This can be done several ways, such as:
1. Programmatically by adding a call like `JSch.setConfig("server_host_key", JSch.getConfig("server_host_key") + ",ssh-rsa")` to your application.
2. By adding a system property like `jsch.server_host_key= ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256,ssh-rsa` to your application.
3. Making use of the `OpenSSHConfig` type `ConfigRepository` implementation with an appropriately configured OpenSSH client config file in your application.

Thanks,
Jeremy

**Comment by gianielsevier** [comment]
Hi @norrisjeremy,

Awesome, many thanks for your prompt reply.
That worked like charm.

Kind regards,
Giani Segatto
