### ISSUE TITLE
JSchAlgoNegoFailException: Algorithm negotiation fail: serverProposal="ssh-rsa"

### ISSUE THREAD

**Issue by Vakhturov** [mwiede/jsch#260]
Hello dear Team,

our customers are using an old SFTP server for their reasons, that is using an outdated key encryption "ssh-rsa". This is only supported by the old version of original JSCH library 2018, so that we are forced to use it as a workaround.

Would it be possible to extend the supported algorithm list with that outdated one?

Here is the complete stack trace:

```
Cannot connect to sftp://<xxx>

org.apache.camel.component.file.GenericFileOperationFailedException: 
Cannot connect to sftp://<xxx>

     at org.apache.camel.component.file.remote.SftpOperations.connect(SftpOperations.java:137) ~[camel-ftp-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.remote.RemoteFileProducer.connectIfNecessary(RemoteFileProducer.java:184) ~[camel-ftp-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.remote.RemoteFileProducer.preWriteCheck(RemoteFileProducer.java:133) ~[camel-ftp-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.GenericFileProducer.processExchange(GenericFileProducer.java:113) ~[camel-file-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.remote.RemoteFileProducer.process(RemoteFileProducer.java:61) ~[camel-ftp-3.20.0.jar:3.20.0]
     at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:66) ~[camel-support-3.20.0.jar:3.20.0]
     at org.apache.camel.processor.SendProcessor.lambda$process$2(SendProcessor.java:195) ~[camel-core-processor-3.20.0.jar:3.20.0]
     at org.apache.camel.support.cache.DefaultProducerCache.doInAsyncProducer(DefaultProducerCache.java:327) ~[camel-support-3.20.0.jar:3.20.0]
     at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:194) ~[camel-core-processor-3.20.0.jar:3.20.0]
     at org.apache.camel.processor.errorhandler.RedeliveryErrorHandler$SimpleTask.run(RedeliveryErrorHandler.java:477) ~[camel-core-processor-3.20.0.jar:3.20.0]
     at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:181) ~[camel-base-engine-3.20.0.jar:3.20.0]
     at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59) ~[camel-base-engine-3.20.0.jar:3.20.0]
     at org.apache.camel.processor.Pipeline.process(Pipeline.java:165) ~[camel-core-processor-3.20.0.jar:3.20.0]
     at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:392) ~[camel-base-engine-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:492) ~[camel-file-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:245) ~[camel-file-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:206) ~[camel-file-3.20.0.jar:3.20.0]
     at org.apache.camel.support.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:202) ~[camel-support-3.20.0.jar:3.20.0]
     at org.apache.camel.support.ScheduledPollConsumer.run(ScheduledPollConsumer.java:116) ~[camel-support-3.20.0.jar:3.20.0]
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
     at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
     at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.jcraft.jsch.JSchAlgoNegoFailException: Algorithm negotiation fail: algorithmName="server_host_key" jschProposal="ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256" serverProposal="ssh-rsa"
     at com.jcraft.jsch.KeyExchange.guess(KeyExchange.java:147) ~[jsch-0.2.5.jar:0.2.5]
     at com.jcraft.jsch.Session.receive_kexinit(Session.java:602) ~[jsch-0.2.5.jar:0.2.5]
     at com.jcraft.jsch.Session.connect(Session.java:334) ~[jsch-0.2.5.jar:0.2.5]
     at org.apache.camel.component.file.remote.SftpOperations.tryConnect(SftpOperations.java:160) ~[camel-ftp-3.20.0.jar:3.20.0]
     at org.apache.camel.support.task.BlockingTask.lambda$run$0(BlockingTask.java:40) ~[camel-support-3.20.0.jar:3.20.0]
     at org.apache.camel.support.task.ForegroundTask.run(ForegroundTask.java:93) ~[camel-support-3.20.0.jar:3.20.0]
     at org.apache.camel.support.task.BlockingTask.run(BlockingTask.java:40) ~[camel-support-3.20.0.jar:3.20.0]
     at org.apache.camel.component.file.remote.SftpOperations.connect(SftpOperations.java:135) ~[camel-ftp-3.20.0.jar:3.20.0]
     ... 24 common frames omitted
```

Thank you in advance for your reply.

**Comment by mwiede** [comment]
This is explained in the FAQ https://github.com/mwiede/jsch#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server.
You can set `JSch.setConfig("server_host_key", JSch.getConfig("server_host_key") + ",ssh-rsa")` globally or you can configure it using system properties (see https://github.com/mwiede/jsch/wiki/Jsch-Configuration#3-java-system-properties)

**Comment by YSavitski** [comment]
Hello together,

we are also facing with the same problem of missing "ssh-rsa"

**Comment by Vakhturov** [comment]
Hi @mwiede, thanks for the note. 

@YSavitski We are using Apache Camel, which is running JSCH under the hood. So, that setting the env variable helped in this way:
`-Djsch.server_host_key=ssh-rsa`
