### ISSUE TITLE
Auth cancel for methods 'publickey,password'

### ISSUE THREAD

**Issue by mavjason** [mwiede/jsch#286]
I am trying to connect using ANT SSHEXEC. (**Host machine Ubuntu 22.04 , Target Machine  Ubuntu 22.04**)
I have generated SSH-keys using the following command:
ssh-keygen -t rsa -b 2048 -m PEM

I have appended the public key in the authorized_keys file.

I have downloaded the latest jsch version and the file is located under .ant/lib folder

My build.xml file has the same structure with the following:

```
<project name="test" default="test" basedir=".">
  <target name="test">
    <sshexec
      host="xxx.xxx.xxx.xxx"
      knownhosts="/var/lib/jenkins/.ssh/known_hosts"
      username="user"
      keyfile="/var/lib/jenkins/.ssh/id_rsa"
      passphrase="xxxxxxx"
      command="ls -ltra"/>
  </target>
</project>
```

I get this error:

```
BUILD FAILED
/var/lib/jenkins/workspace/Ant-ssh-Job/build.xml:9: com.jcraft.jsch.JSchException: Auth cancel for methods 'publickey,password'
        at com.jcraft.jsch.Session.connect(Session.java:528)
        at com.jcraft.jsch.Session.connect(Session.java:190)
        at org.apache.tools.ant.taskdefs.optional.ssh.SSHBase.openSession(SSHBase.java:349)
        at org.apache.tools.ant.taskdefs.optional.ssh.SSHExec.execute(SSHExec.java:316)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

**Comment by norrisjeremy** [comment]
Hi @mavjason,

Are you sure the passphrase for your SSH key is correct in your build.xml?
Have you manually tested with this ssh key and confirmed that it can be used to connect to your server?

Thanks,
Jeremy

**Comment by mavjason** [comment]
hi @norrisjeremy .
I have used the ssh -i ~/.ssh/id_rsa user@host with the same passphrase and it works .

**Comment by norrisjeremy** [comment]
Hi @mavjason,

I'm not sure how much more assistance we can provide then.
The error message above indicates JSch was unable to decrypt the SSH key using the provided passphrase.

Thanks,
Jeremy

**Comment by mavjason** [comment]
I don't understand the AUTH cancel error

**Comment by mavjason** [comment]
I figured out that the passphrase that i am using contains $.
That's why it does not work.
Using a string with only alphanumeric characters solves the problem.

**Comment by norrisjeremy** [comment]
Hi @mavjason,

Excellent news!
I would suspect the issue with `$` symbols is something to do with Ant itself (possibly trying to treat the value as a variable or something)?

Thanks,
Jeremy
