### ISSUE TITLE
Auth fail with private key in string

### ISSUE THREAD

**Issue by Nikotine1** [mwiede/jsch#33]
I want to use a key to access my SSH server, but I keep getting an Auth Fail error.
This is for an Android application in Kotlin.

```
private fun sshCommand(
            username: String? = "root",
            //password: String? = "xxxxxxxxxx",
            host: String? = "192.168.1.1",
            port: Int = 22,
            command: String?
    ) {
        GlobalScope.launch(Dispatchers.IO) {
            var session: Session? = null
            var channel: ChannelExec? = null

            val privateKey = "-----BEGIN RSA PRIVATE KEY-----\n" +
                    "MIIEowIBAAKCAQEAuwYj4yZ427dxKKksO05+J9tZQJh75KlbfajFuiI2K4RwTQf1\n" +
                    "DCZwxHAsvNikOVd1QpO2KaOovRvaPxtxaa7lfSdakJaYDG3xNkIlC6lu6r2AelVq\n" +
                    "bNEqRwrIbWxO9hfH2a9Bx/ffEolj6aPnclzNuh5cJvGhq0yySiyJZgkdmc1mTV8K\n" +
                    "ZiOiS5Tr5jIBagRyHL5tAEnLr4Jm4I/vrkr9H/wbeo5bASlxHGBpUezMIyBidWpJ\n" +
                    "lbGKn+fEjg5pDpf4dFylNOV8zLWLpEWIXDg4rzmJudeU4Q6CJuExwFyo8v85qYc0\n" +
                    "95DmeLINTQt6yEMFjWdvuOUntviQBU8SODG5mwIBJQKCAQEAtfgi6tlS/0qzSigP\n" +
                    "XExfEgXaTLAJ15AF/bj3vAWcfV5DwJIe22Or/WY5XcveDkdBqI+4KIOPa+O/l1j4\n" +
                    "udqaGOgFFw8QesvV75pNjs5eFNQOTYOKJK/WG5vJ7ezXNKGELb9G7BPESWMVGq1P\n" +
                    "5OSsfbyssEUMAJ2mjVvD9JM/ZTTf6xu2GKyWt9go+NhUQGLKFlQe/aEq4tf1MGQP\n" +
                    "IFpOoLkPY3Y9twK4iYIHiZ2m7BpSufrukkrqrcuttNZ86/ftM0iuPzflSWJjaIQj\n" +
                    "wRhOl1/ilu9GkV8Edcx9LcN/N5GBSRsO7zmgrbZrAgXZo60zlcblDkdBNnJmaHE+\n" +
                    "DBZqLQKBgQD3+xhjIjoX0ooSBpZ7CALXq1AtJ45d010kj0sY041+QgZ+aNouAfAw\n" +
                    "vTowvukdCJtfEgULtVIJkRNS8txe21XQwUFMyz/9Wnonh1RIYLZDhogrx4BLydJu\n" +
                    "69Xp/RNvEgW93j0DG5RCW55N3y+fwMFanB2kzQjDwHAF++yrD4N8KwKBgQDBEmos\n" +
                    "HFSaPBdabhKFH9T1aLQ8cIBzj3H4GGw5Fe7m8akwzwjfWHZ0fH0GKSGnGaLZB84B\n" +
                    "kSC6ht+NTABCsoNXd0mI4Y+a5s8onDCNA0VrfuQm1zayVyij+tyqqZWhy2sMQCdG\n" +
                    "EMiGFTS1ARz0O7pSXnZDDva2Ra9n5SbnY15QUQKBgEm5Wkb8VnXI+J2TQX6F11Tf\n" +
                    "52deyXXXDdpvyjfQMPwFypRIr5EjK7t2huvluuz0uJHiwzrVCo049+g6XTD1GYNA\n" +
                    "X4WIiKVEaYFflZj6KFlDq/FW/KDo+V8/McIazm0hCKA7JuU/jPEiKCT9KdWMVSjG\n" +
                    "oQd7OfUB3B10aPSV6NHjAoGBAIzj7Jy6ukcJQXlXPfJxLLMVDebqT+WgBw79ELQJ\n" +
                    "Fh4l+AEFyDRHeQjlOKOheWwZoFkvNXbD2Zze9ijWmGgFuco0c+5Du9Hmsthx+epc\n" +
                    "VUCa3dcnbRpbRyuNjEUvpIrSteZYVAKyTSOS7xxM6513sXpgm30K62JqM+QIFXhr\n" +
                    "G09dAoGBAOvogarpounrMCPTAtcyiYtoiVoV5X1zZKkEP9yvJJlZobKsIo8Fk+mP\n" +
                    "GkcnIp+sKaGq8j/lBtxt3jWQSI/z7OFFm++0CYQDRmdqMhxszfYmeOX/e8c1V/rz\n" +
                    "2iwuMcc2qWAlifsHeLubUGIn0f7nWURR9cgYekE8h5ad7KKO3Q8O\n" +
                    "-----END RSA PRIVATE KEY-----\n"

            try {
                JSch().addIdentity("blabla123", privateKey.toByteArray(), null, null)
                session = JSch().getSession(username, host, port)
                //session.setPassword(password)
                session.setConfig("StrictHostKeyChecking", "no")
                session.connect()
                channel = session.openChannel("exec") as ChannelExec
                channel.setCommand(command)
                val responseStream = ByteArrayOutputStream()
                channel.outputStream = responseStream
                channel.connect()
                while (channel.isConnected) {
                    Thread.sleep(100)
                }
                val responseString = String(responseStream.toByteArray())
                println(responseString)
            } finally {
                session?.disconnect()
                channel?.disconnect()
            }
        }
    }
```

Log in Android Studio:
```
W/System.err: INFO: Connecting to 192.168.1.1 port 22
W/System.err: INFO: Connection established
W/System.err: INFO: Remote version string: SSH-2.0-dropbear
W/System.err: INFO: Local version string: SSH-2.0-JSCH-0.1.54
W/System.err: INFO: CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
W/System.err: INFO: CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
W/System.err: INFO: CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
W/System.err: INFO: SSH_MSG_KEXINIT sent
    INFO: SSH_MSG_KEXINIT received
W/System.err: INFO: kex: server: curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,kexguess2@matt.ucc.asn.au
W/System.err: INFO: kex: server: ssh-rsa
    INFO: kex: server: aes128-ctr,aes256-ctr
W/System.err: INFO: kex: server: aes128-ctr,aes256-ctr
    INFO: kex: server: hmac-sha1,hmac-sha2-256
W/System.err: INFO: kex: server: hmac-sha1,hmac-sha2-256
    INFO: kex: server: none
W/System.err: INFO: kex: server: none
    INFO: kex: server: 
W/System.err: INFO: kex: server: 
W/System.err: INFO: kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
W/System.err: INFO: kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
W/System.err: INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
W/System.err: INFO: kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
W/System.err: INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
W/System.err: INFO: kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
    INFO: kex: client: none
W/System.err: INFO: kex: client: none
W/System.err: INFO: kex: client: 
    INFO: kex: client: 
W/System.err: INFO: kex: server->client aes128-ctr hmac-sha1 none
W/System.err: INFO: kex: client->server aes128-ctr hmac-sha1 none
W/System.err: INFO: SSH_MSG_KEXDH_INIT sent
W/System.err: INFO: expecting SSH_MSG_KEXDH_REPLY
W/System.err: INFO: ssh_rsa_verify: signature true
W/System.err: WARN: Permanently added '192.168.1.1' (RSA) to the list of known hosts.
W/System.err: INFO: SSH_MSG_NEWKEYS sent
W/System.err: INFO: SSH_MSG_NEWKEYS received
W/System.err: INFO: SSH_MSG_SERVICE_REQUEST sent
W/System.err: INFO: SSH_MSG_SERVICE_ACCEPT received
W/System.err: INFO: Authentications that can continue: publickey,keyboard-interactive,password
W/System.err: INFO: Next authentication method: publickey
W/System.err: INFO: Authentications that can continue: password
    INFO: Next authentication method: password
W/System.err: INFO: Disconnecting from 192.168.1.1 port 22
E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.example.ps4nuker, PID: 9354
    com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:519)
        at com.jcraft.jsch.Session.connect(Session.java:183)
        at com.example.ps4nuker.MainActivity$sshCommand$1.invokeSuspend(MainActivity.kt:101)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
I believe the private key is in the right format for JSch to understand.
The connection works perfectly when I use a password, or when I use the same private key in Mobaxterm.
How can I get it to work with the private key in a string?

**Comment by mwiede** [comment]
you have 2 Jsch instances. you have to change it like this:

```
val jSch = JSch()
jSch.addIdentity("blabla123", privateKey.toByteArray(), null, null)
session = jSch.getSession(username, host, port)
```

**Comment by Nikotine1** [comment]
Yes! Thank you! I guess I combined code where they used the password, with other code for the key, not realizing this created a new instance.
