### ISSUE TITLE
jsch.addIdentity() fails with IndexOutOfBounds when private key has CRLF line breaks

### ISSUE THREAD

**Issue by AmairK00** [mwiede/jsch#369]
Hi,

The below code does not work since the latest 0.2.10 release. Up to 0.2.9 this is working fine. 
I don't have much idea on the library, so I cannot say if I have to use something different or if there is a configuration. 
Please let me know.

```
String pkey="Key with CRLF linebreaks'
Jsch jsch = new Jsch()
jsch.addIndentity("file",pkey.getBytes(),null,null) // fails with ArrayIndexOutofBoundsException
```
logs:
```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 1190 out of bounds for byte[1176]
	at java.base/java.lang.System.arraycopy(Native Method)
	at com.jcraft.jsch.KeyPairRSA.parse(KeyPairRSA.java:337)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:1126)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:44)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:515)
	at com.test.jsch.JschMain.main(JschMain.java:60)

Exception in thread "main" com.jcraft.jsch.JSchException: invalid privatekey
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:1129)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:44)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:515)
	at com.test.jsch.JschMain.main(JschMain.java:60)
```

**Comment by gmicherinas** [comment]
Hi all, 
As OP said, my tests work as intended till 0.2.9. with 0.2.10 and I got this exact error. 
I use jsch as part of  camel-ftp with PK authentication as well. 

I too had my keys with CRLF line endings. After changing them to LF my tests passed. 

So I guess, I can also validate that the root cause should be that keys with CRLF aren't parsed correctly as @AmairK00 said.

**Comment by gmicherinas** [comment]
> 

Mine starts with `-----BEGIN OPENSSH PRIVATE KEY-----`

**Comment by norrisjeremy** [comment]
Ok, I have replicated this locally and will try to determine a solution.

**Comment by AmairK00** [comment]
It starts with `----BEGIN RSA PRIVATE KEY-----`. Yeah the key works when I change it to only '\n'

**Comment by norrisjeremy** [comment]
Hi @AmairK00 & @gmicherinas,

Actually we have made a new 0.2.11 release that hopefully fixes this regression: can you test and confirm?

Thanks,
Jeremy

**Comment by AmairK00** [comment]
Hi @norrisjeremy 

The fix works for me. Thanks for the update.
