### ISSUE TITLE
sftp server failed to read file

### ISSUE THREAD

**Issue by bruceyung** [mwiede/jsch#491]
I encountered an exception while using SFTP to read files from the SUSE Linux server:  “4  at com.jcraft.jsch.ChannelSftp._get(ChannelSftp.java:1184)_       at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:1030)_      at com.jcraft.jsch.ChannelSftp.get(ChannelSftp.java:1008)_ ” .  What confuses me is that the description of the exception is too simple, and I cannot determine the cause of the problem.  jsch version:  0.2.16

**Comment by norrisjeremy** [comment]
Hi @bruceyung,

1. Can you please provide a full backtrace?
2. Can you please provide a full copy of JSch logs?
3. Can you please confirm the version of JSch you are using?
-- The limited backtrace info you provided could not have come from the 0.2.16 release.

Thanks,
Jeremy

**Comment by bruceyung** [comment]
> Hi @norrisjeremy ,
> 
> 1. Can you please provide a full backtrace?
   code example：
   	ChannelSftp sftp = null;
	ByteArrayOutputStream output = null;
        try {
            sftp = this.sftpPool.getChannelSftp(code);
	   output = new ByteArrayOutputStream();
            sftp.get(fileFullName, output);
        } catch (SftpException e) {
            log.error("sftp server: failed to read file!" ,e);
        } 
    expalin: SftpPool is an object pool.  (org.apache.commons.pool2.impl.GenericKeyedObjectPool)
                  <dependency>
                     <groupId>org.apache.commons</groupId>
                     <artifactId>commons-pool2</artifactId>
                    <version>2.11.1</version>
                 </dependency>
> 2. Can you please provide a full copy of JSch logs?
[Log Detail.txt](https://github.com/mwiede/jsch/files/14106200/Log.Detail.txt)
     Please refer to the attachment！
> 3. Can you please confirm the version of JSch you are using?
>    -- The limited backtrace info you provided could not have come from the 0.2.16 release.
    Confirmed!
    <dependency>
         <groupId>com.github.mwiede</groupId>
         <artifactId>jsch</artifactId>
         <version>0.2.16</version>
   </dependency>
> 
> Thanks

**Comment by norrisjeremy** [comment]
Hi @bruceyung,

Unfortunately I don't think I can provide much assistance to you:

1. The exception message from your the log file you provided does not appear to match any exception message that JSch would have thrown.
2. The line numbers present in the backtrace for JSch classes does not correlate to locations in the 0.2.16 JSch release that could possibly be cause an exception.
3. Because of the two items above, I can only conclude that either you are mistaken about the version of JSch that your application is using, or the version you are using is modified in some manner.
4. Additionally the log file you provided is lacks internal JSch logging messages that we would need to help you out.

Thanks,
Jeremy

**Comment by bruceyung** [comment]
Hi @norrisjeremy

Thank you for taking your valuable time. After repeated confirmation, the version that caused the problem was 0.1.55, which was upgraded to 0.2.16 and resolved the issue.

Thanks
