### ISSUE TITLE
sftp server die thread blocking during sftp ls execution

### ISSUE THREAD

**Issue by txran** [mwiede/jsch#543]
<img width="467" alt="_20240416215853" src="https://github.com/mwiede/jsch/assets/61140399/05a78e1f-53fe-4586-9a22-ce399eda079d">
this is jstack blocking   thread

**Comment by txran** [comment]
version 0.1.54

**Comment by norrisjeremy** [comment]
Hi @txran,

0.1.54 is a very old version that was released by the original JSch maintainer prior to this fork's existence.
Can you please confirm whether or not this is still an issue with our current release ([0.2.17](https://github.com/mwiede/jsch/releases/tag/jsch-0.2.17))?

Thanks,
Jeremy

**Comment by emp-java** [comment]
I also met this issue with        
<dependency>
                <groupId>com.jcraft</groupId>
                <artifactId>jsch</artifactId>
                <version>0.1.55</version>
</dependency>

"eaf.sync-data1" #1464 prio=5 os_prio=0 tid=0x0000fffa708de800 nid=0xa3ea0 in Object.wait() [0x0000fff8eedfd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at java.lang.Object.wait(Native Method)
	at java.io.PipedInputStream.read(PipedInputStream.java:326)
	- eliminated <0x000000068c804b88> (a com.jcraft.jsch.Channel$MyPipedInputStream)
	at java.io.PipedInputStream.read(PipedInputStream.java:377)
	- locked <0x000000068c804b88> (a com.jcraft.jsch.Channel$MyPipedInputStream)
	at java.io.InputStream.skip(InputStream.java:224)
	at com.jcraft.jsch.ChannelSftp.skip(ChannelSftp.java:2921)
	at com.jcraft.jsch.ChannelSftp.access$600(ChannelSftp.java:36)
	at com.jcraft.jsch.ChannelSftp$RequestQueue.cancel(ChannelSftp.java:1270)
	at com.jcraft.jsch.ChannelSftp$2.read(ChannelSftp.java:1501)
	at com.jcraft.jsch.ChannelSftp$2.read(ChannelSftp.java:1364)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:166)
	at org.springframework.util.FileCopyUtils.copy(FileCopyUtils.java:112)
	at org.springframework.util.FileCopyUtils.copyToByteArray(FileCopyUtils.java:152)

**Comment by norrisjeremy** [comment]
Hi @emp-java,

0.1.55 is a very old version that was released by the original JSch maintainer prior to this fork's existence.
Can you please confirm whether or not this is still an issue with our current release ([0.2.17](https://github.com/mwiede/jsch/releases/tag/jsch-0.2.17))?

Thanks,
Jeremy

**Comment by Kugin** [comment]
I also met this issue with 
com.github.mwiede
jsch
0.2.23

more information:
java.lang.Thread.State: TIMED_WAITING
   @ java.lang.Object.wait(Native Method)
   @ java.io.PipedInputStream.read(PipedInputStream.java:326)
   @ java.io.PipedInputStream.read(PipedInputStream.java:377)
   @ com.jcraft.jsch.ChannelSftp.fill(ChannelSftp.java:2866)
   @ com.jcraft.jsch.ChannelSftp.header(ChannelSftp.java:2894)
   @ com.jcraft.jsch.ChannelSftp._realpath(ChannelSftp.java:2276)
   @ com.jcraft.jsch.ChannelSftp.cd(ChannelSftp.java:330)
