### ISSUE TITLE
Regarding No Such Method in bouncycastle

### ISSUE THREAD

**Issue by muthukumar2k** [mwiede/jsch#581]
Dear Team,
I am using bouncycastle 1.78.1 jars bctest-jdk18on-1.78.1.jar. While establishing TLS connection, i am getting this exception,

[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: java.lang.NoSuchMethodError: 'org.bouncycastle.crypto.SavableDigest org.bouncycastle.crypto.digests.SHA256Digest.newInstance(org.bouncycastle.crypto.Digest)'|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.crypto.impl.bc.BcTlsCrypto.cloneDigest(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.crypto.impl.bc.BcTlsHash.cloneHash(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.DeferredHash.cloneHash(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.DeferredHash.cloneHash(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.DeferredHash.forkPRFHash(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsUtils.getCurrentPRFHash(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsServerProtocol.send13ServerHelloCoda(Unknown Source)|
[09:31:48:285]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(Unknown Source)|
[09:31:48:286]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(Unknown Source)|
[09:31:48:286]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsProtocol.processRecord(Unknown Source)|
[09:31:48:286]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.RecordStream.readRecord(Unknown Source)|
[09:31:48:286]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsProtocol.safeReadRecord(Unknown Source)|
[09:31:48:286]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsProtocol.blockForHandshake(Unknown Source)|
[09:31:48:286]|[06-18-2024]|[SYSERR]|[INFO]|[96]: 	at org.bouncycastle.tls.TlsServerProtocol.accept(Unknown Source)|

What might be the reason for the issue ?

**Comment by norrisjeremy** [comment]
Hi @muthukumar2k,

I'm not sure what this has to do with JSch: Bouncy Castle is a different project.
You likely will need to ask their project for assistance.

Thanks,
Jeremy
