### ISSUE TITLE
Auth fail for methods 'publickey,gssapi-keyex,gssapi-with-mic,password'

### ISSUE THREAD

**Issue by origin-meta** [mwiede/jsch#590]
Hello authors
When I use JSCH 0.2.18 to access the target machine with a private key (ssh version: OpenSSH 6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013), I throw "Auth fail for methods' public key, gssapi keyex, gssapi with mic, password '". However, when I switch to 0.1.72, it can be accessed normally. Please help me check this issue. Thank you very much

**Comment by mwiede** [comment]
Please paste your log.

I guess it's because of #75 which was introduced with 0.2.0

see FAQ https://github.com/mwiede/jsch?tab=readme-ov-file#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server

**Comment by yuzeboya** [comment]
I also encountered the same problem, using jsch 0.2.18, running the following code in openssh7.4 can be normal connection, in openssh8.2, reported the same error

`jsch.addIdentity("/root/.ssh/id_rsa");
        session = jsch.getSession(conn.getLoginUser(), conn.getHost(), conn.getPort());
        session.setConfig("StrictHostKeyChecking", "no");`

**Comment by L272893453** [comment]
I also encountered the same problem， log:
`com.jcraft.jsch.JSchException: Auth fail for methods 'publickey,gssapi-keyex,gssapi-with-mic,password'
        at com.jcraft.jsch.Session.connect(Session.java:520) ~[jsch-0.2.17.jar!/:0.2.17]
        at com.jcraft.jsch.Session.connect(Session.java:198) ~[jsch-0.2.17.jar!/:0.2.17]
        at cn.com.winning.mmop.InstallUtils$LinuxBashShell.getSession(InstallUtils.java:395) ~[classes!/:na]
        at cn.com.winning.mmop.InstallUtils$LinuxBashShell.isAvailableSvr(InstallUtils.java:445) ~[classes!/:na]
        at cn.com.winning.mmop.steps.ServerConfigStep.checkServer(ServerConfigStep.java:113) [classes!/:na]
        at cn.com.winning.mmop.steps.ServerConfigStep.lambda$validate$0(ServerConfigStep.java:99) [classes!/:na]
        at cn.com.winning.mmop.common.core.ObjectRunnable.run(ObjectRunnable.java:21) ~[winning-mmop-common-1.0.0-SNAPSHOT.jar!/:na]
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[na:1.8.0_391]
        at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[na:1.8.0_391]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_391]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[na:1.8.0_391]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[na:1.8.0_391]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[na:1.8.0_391]`

`<dependency>
            <groupId>com.github.mwiede</groupId>
            <artifactId>jsch</artifactId>
            <version>0.2.17</version>
        </dependency>`

**Comment by norrisjeremy** [comment]
Folks,

Continually piling on with "me too" does nothing to help us troubleshoot your issues.
As @mwiede stated earlier, if you like us to try and help you, then you will need to enable logging in JSch and then include those logs in your problem report.

And to also reiterate: the problem is almost certainly related to the fact that the servers to which you are connecting only allow old/insecure crypto algorithms that JSch deliberately disables by default, and thus you will have to determine which old/insecure crypto algorithms your servers are utilizing and then programmatically enable those old/insecure crypto algorithms in JSch as we outline in our FAQs.

@mwiede Do you think we should setup some templates for when folks open issues, to better encourage inclusion of logs, reminders to check & confirm common FAQs before opening an issue, etc.?

Thanks,
Jeremy

**Comment by origin-meta** [comment]
very thanks. I understand why there are errors when connecting to lower versions of SSH. Guys, you can take a look at the documentation. 
https://github.com/mwiede/jsch?tab=readme-ov-file#why-do-ssh-rsa-type-keys-not-work-with-this-jsch-fork-and-my-server
```
Why do ssh-rsa type keys not work with this JSch fork and my server?
As of the [0.2.0](https://github.com/mwiede/jsch/releases/tag/jsch-0.2.0) release, the RSA/SHA1 signature algorithm is disabled by default.
SHA1 is no longer considered secure by the general cryptographic community and this JSch fork strives to maintain secure choices for default algorithms that it will utilize.
This also follows the lead of the OpenSSH project in which they disabled RSA/SHA1 signatures by default as of [OpenSSH release 8.8](https://www.openssh.com/txt/release-8.8).
```
