### ISSUE TITLE
com.jcraft.jsch.JSchSessionDisconnectException: SSH_MSG_DISCONNECT: 2 Too many authentication failures: 4

### ISSUE THREAD

**Issue by Praj777-am** [mwiede/jsch#608]
Seeing above exception thrown during connect for a Host only with Jsch version - 0.x but the same host connects successfully with Jsch version 0.1.54
Error logs at JSch - 0.x -
```
Remote version string: SSH-2.0-SFTP 2.0 Server
Local version string: SSH-2.0-JSCH_0.2.18
CheckCiphers: chacha20-poly1305@openssh.com
CheckKexes: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
sntrup761x25519-sha512@openssh.com is not available.
curve25519-sha256 is not available.
curve25519-sha256@libssh.org is not available.
curve448-sha512 is not available.
CheckSignatures: ssh-ed25519,ssh-ed448
ssh-ed25519 is not available.
ssh-ed448 is not available.
SSH_MSG_KEXINIT sent
SSH_MSG_KEXINIT received
ext-info messaging supported by server
server proposal: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256,ext-info-s
server proposal: host key algorithms: rsa-sha2-512,rsa-sha2-256,ssh-rsa
server proposal: ciphers c2s: aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc
server proposal: ciphers s2c: aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc
server proposal: MACs c2s: hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha1
server proposal: MACs s2c: hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha1
server proposal: compression c2s: none
server proposal: compression s2c: none
server proposal: languages c2s: 
server proposal: languages s2c: 
client proposal: KEX algorithms: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
client proposal: host key algorithms: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
client proposal: ciphers c2s: blowfish-cbc,3des-cbc,aes128-cbc,aes192-cbc,aes256-cbc,3des-ctr,aes256-ctc,arcfour,arcfour128,arcfour256,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
client proposal: ciphers s2c: blowfish-cbc,3des-cbc,aes128-cbc,aes192-cbc,aes256-cbc,3des-ctr,aes256-ctc,arcfour,arcfour128,arcfour256,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
client proposal: MACs c2s: hmac-md5,hmac-md5-96,hmac-sha1-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
client proposal: MACs s2c: hmac-md5,hmac-md5-96,hmac-sha1-96,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
client proposal: compression c2s: none
client proposal: compression s2c: none
client proposal: languages c2s: 
client proposal: languages s2c: 
kex: algorithm: ecdh-sha2-nistp256
kex: host key algorithm: ssh-rsa
kex: server->client cipher: aes128-cbc MAC: hmac-sha2-256-etm@openssh.com compression: none
kex: client->server cipher: aes128-cbc MAC: hmac-sha2-256-etm@openssh.com compression: none
SSH_MSG_KEX_ECDH_INIT sent
expecting SSH_MSG_KEX_ECDH_REPLY
ssh_rsa_verify: ssh-rsa signature true
Permanently added 'test.transac.com' (RSA) to the list of known hosts.
SSH_MSG_NEWKEYS sent 
SSH_MSG_NEWKEYS received
SSH_MSG_EXT_INFO sent 
SSH_MSG_SERVICE_REQUEST sent
SSH_MSG_EXT_INFO received 
server-sig-algs=<ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256,ssh-rsa>
SSH_MSG_SERVICE_ACCEPT received
Authentications that can continue: publickey,password
Next authentication method: publickey
Authentications that can continue: password
Next authentication method: password
Disconnecting from test.transac.com port 22
Could not retrieve client for test.transac.com
 Caught exception during connect to host test.transac.com
Caused by: com.jcraft.jsch.JSchSessionDisconnectException: SSH_MSG_DISCONNECT: 2 Too many authentication failures: 4
        at com.jcraft.jsch.Session.read(Session.java:1316) ~[jsch-0.2.18.jar:0.2.18]
        at com.jcraft.jsch.UserAuthPassword.start(UserAuthPassword.java:88) ~[jsch-0.2.18.jar:0.2.18]
        at com.jcraft.jsch.Session.connect(Session.java:479) ~[jsch-0.2.18.jar:0.2.18]
        at SFTPResource.connect(SFTPResource.java:131) ~[EICheshire-4.0.jar:?]
        ... 16 more
```

Whereas connect succeeds on 0.1.54 version -

```
Remote version string: SSH-2.0-SFTP 2.0 Server
Local version string: SSH-2.0-JSCH-0.1.54
CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
SSH_MSG_KEXINIT received
kex: server: curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group18-sha512,diffie-hellman-group17-sha512,diffie-hellman-group16-sha512,diffie-hellman-group15-sha512,diffie-hellman-group14-sha256,ext-info-s
kex: server: rsa-sha2-512,rsa-sha2-256,ssh-rsa
kex: server: aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc
kex: server: aes256-cbc,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc
kex: server: hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha1
kex: server: hmac-sha2-512,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha1
kex: server: none
kex: server: none
kex: server:
kex: server:
kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
kex: client: none
kex: client: none
kex: client:
kex: client:
kex: server->client aes128-ctr hmac-sha1 none
kex: client->server aes128-ctr hmac-sha1 none
SSH_MSG_KEX_ECDH_INIT sent
expecting SSH_MSG_KEX_ECDH_REPLY
ssh_rsa_verify: signature true
Permanently added 'test.transac.com' (RSA) to the list of known hosts.
SSH_MSG_NEWKEYS sent
SSH_MSG_NEWKEYS received
SSH_MSG_SERVICE_REQUEST sent
SSH_MSG_SERVICE_ACCEPT received
Authentications that can continue: publickey,password
Next authentication method: publickey
Authentications that can continue: password
Next authentication method: password
Authentication succeeded (password).
Successfully connected to test.transac.com:22
```

From logs I dont see any algorithm negotiations failures or related to that, do we know any potential breaking issue with latest JSch version?
There is no change with password cred that goes for these 2 requests and no code change wrt JSch from java side, only differenc eis the version of Jsch

**Comment by norrisjeremy** [comment]
Hi @Praj777-am,

My suspicion is that JSch is attempting to perform multiple publickey auth attempts (due to whatever SSH identity keys you have loaded) and the server to which you are connecting limits the number of failed auth attempts before it disconnects a client. Since modern JSch by default supports RSA/SHA2, it can perform multiple auth attempts for the same RSA type key (rsa-sha2-256, rsa-sha2-512, etc.), which can quickly exhaust the number of failed auth attempt limits servers will enforce.

If you enable debug logging, that will generate additional logging from the `UserAuthPublicKey` class which could help confirm my suspicion.

Additionally, if you know that you want to perform password based authentication and not publickey based authentication, then I would suggest simply disabling publickey based authentication altogether, which would likely avoid this problem altogether.

Thanks,
Jeremy

**Comment by Praj777-am** [comment]
In this case, I am sure of password authentication, how cna I disable public Key for this request? is there a command I can set from Jsch client? or is that something I need to ask client to set on server? I will check client for debug logs...

**Comment by norrisjeremy** [comment]
Hi @Praj777-am,

You should be able to enable only password based authentication by using `session.setConfig("PreferredAuthentications", "password")`.

Thanks,
Jeremy

**Comment by Praj777-am** [comment]
thanks, that helped connecting successfully with Jsch 0.x
