### ISSUE TITLE
Password Auth failing : an exception during authentication

### ISSUE THREAD

**Issue by jensjp** [mwiede/jsch#726]
On connecting to a remote sftp server the password auth flow is failing with a IO error. 

Jsch version : 0.2.21
Java : 11

ssh-rsa is enabled as the server seems to be not implementing the latest rsa-ssh2 algorithms.

Jsch is used from the apache camel sftp component. Any pointers to further debug this issue ?

 o.a.c.c.file.remote.SftpOperations       : JSCH -> Connecting to <ip-redacted> port 54322
 o.a.c.c.file.remote.SftpOperations       : JSCH -> Connection established
 o.a.c.c.file.remote.SftpOperations       : JSCH -> Remote version string: SSH-2.0-Serv-U_15.3.1.155
 o.a.c.c.file.remote.SftpOperations       : JSCH -> Local version string: SSH-2.0-JSCH_0.2.21
 o.a.c.c.file.remote.SftpOperations       : JSCH -> CheckCiphers: chacha20-poly1305@openssh.com
 o.a.c.c.file.remote.SftpOperations       : JSCH -> CheckKexes: sntrup761x25519-sha512@openssh.com,curve25519-sha256,curve25519-sha256@libssh.org,curve448-sha512
 o.a.c.c.file.remote.SftpOperations       : JSCH -> CheckSignatures: ssh-ed25519,ssh-ed448
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_KEXINIT sent
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_KEXINIT received
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: KEX algorithms: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: host key algorithms: ssh-rsa
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: ciphers c2s: aes128-cbc,rijndael128-cbc,aes192-cbc,rijndael192-cbc,aes256-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: ciphers s2c: aes128-cbc,rijndael128-cbc,aes192-cbc,rijndael192-cbc,aes256-cbc,rijndael256-cbc,rijndael-cbc@lysator.liu.se,rijndael-cbc@lysator.liu.se,aes128-ctr,aes192-ctr,aes256-ctr
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: MACs c2s: hmac-md5,hmac-sha1,hmac-sha1-96,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: MACs s2c: hmac-md5,hmac-sha1,hmac-sha1-96,hmac-sha2-256,hmac-sha2-256-96,hmac-sha2-512,hmac-sha2-512-96
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: compression c2s: zlib,none
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: compression s2c: zlib,none
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: languages c2s: 
 o.a.c.c.file.remote.SftpOperations       : JSCH -> server proposal: languages s2c: 
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: KEX algorithms: diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,ext-info-c,kex-strict-c-v00@openssh.com
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: host key algorithms: ssh-rsa,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,rsa-sha2-512,rsa-sha2-256
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: ciphers c2s: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: ciphers s2c: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: MACs c2s: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: MACs s2c: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: compression c2s: none
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: compression s2c: none
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: languages c2s: 
 o.a.c.c.file.remote.SftpOperations       : JSCH -> client proposal: languages s2c: 
 o.a.c.c.file.remote.SftpOperations       : JSCH -> kex: algorithm: diffie-hellman-group1-sha1
 o.a.c.c.file.remote.SftpOperations       : JSCH -> kex: host key algorithm: ssh-rsa
 o.a.c.c.file.remote.SftpOperations       : JSCH -> kex: server->client cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
 o.a.c.c.file.remote.SftpOperations       : JSCH -> kex: client->server cipher: aes128-ctr MAC: hmac-sha2-256 compression: none
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_KEXDH_INIT sent
 o.a.c.c.file.remote.SftpOperations       : JSCH -> expecting SSH_MSG_KEXDH_REPLY
 o.a.c.c.file.remote.SftpOperations       : JSCH -> ssh_rsa_verify: ssh-rsa signature true
 o.a.c.c.file.remote.SftpOperations       : JSCH -> Permanently added '[ip-redacted]:54322' (RSA) to the list of known hosts.
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_NEWKEYS sent
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_NEWKEYS received
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_SERVICE_REQUEST sent
 o.a.c.c.file.remote.SftpOperations       : JSCH -> SSH_MSG_SERVICE_ACCEPT received
 o.a.c.c.file.remote.SftpOperations       : JSCH -> Authentications that can continue: password
 o.a.c.c.file.remote.SftpOperations       : JSCH -> Next authentication method: password
 o.a.c.c.file.remote.SftpOperations       : JSCH -> an exception during authentication
java.io.IOException: End of IO Stream Read
java.io.IOException: End of IO Stream Read
	at com.jcraft.jsch.IO.getByte(IO.java:97)
	at com.jcraft.jsch.Session.read(Session.java:1231)
	at com.jcraft.jsch.UserAuthPassword.start(UserAuthPassword.java:88)
	at com.jcraft.jsch.Session.connect(Session.java:479)
	at org.apache.camel.component.file.remote.SftpOperations.tryConnect(SftpOperations.java:160)
	at org.apache.camel.support.task.BlockingTask.lambda$run$0(BlockingTask.java:40)
	at org.apache.camel.support.task.ForegroundTask.run(ForegroundTask.java:93)
	at org.apache.camel.support.task.BlockingTask.run(BlockingTask.java:40)
	at org.apache.camel.component.file.remote.SftpOperations.connect(SftpOperations.java:135)
	at org.apache.camel.component.file.remote.RemoteFileConsumer.connectIfNecessary(RemoteFileConsumer.java:231)
	at org.apache.camel.component.file.remote.SftpConsumer.doStart(SftpConsumer.java:68)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.support.service.ServiceHelper.startService(ServiceHelper.java:113)
	at org.apache.camel.impl.engine.AbstractCamelContext.startService(AbstractCamelContext.java:3759)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRouteConsumers(InternalRouteStartupManager.java:401)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartRouteConsumers(InternalRouteStartupManager.java:319)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.safelyStartRouteServices(InternalRouteStartupManager.java:213)
	at org.apache.camel.impl.engine.InternalRouteStartupManager.doStartOrResumeRoutes(InternalRouteStartupManager.java:147)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by jensjp** [comment]
I have found the issue, this is due to password getting corrupted in my java camel route builder. Resolved the issue with wrapping the function in RAW().

Link for anyone facing similar issues.

https://camel.apache.org/manual/faq/how-do-i-configure-endpoints.html#HowdoIconfigureendpoints-Configuringparametervaluesusingrawvalues
